# Generated by Django 5.1.2 on 2024-11-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
